[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "https://coconut-motley-sceptre.glitch.me/api/:splat"
#to = "https://ebiwoni-api.netlify.app/api/:splat"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
